const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const path=require('node:path');
function app(){
 const source=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');const code=source.slice(source.indexOf('const fieldTypeLabels='),source.indexOf('// ── VERBAS LIST'));
 const nodes={'ftpl-edit-name-t':{value:'Novo nome'},'ftpl-edit-type-t':{value:'combobox'},'ftpl-item-list-s':{innerHTML:''}},writes=[],messages=[];
 const S={fieldTemplates:[{id:'t',atividade_id:'s',scope:'item',field_name:'Antigo',field_type:'combobox',options:['A','B'],order_num:2},{id:'u',atividade_id:'s',scope:'item',field_name:'Outro',order_num:0}],items:[{id:'i',atividade_id:'s',extra_fields:{Antigo:'A',Observação:'Preservada'}}],subitems:[]};
 const options=[{value:'B'},{value:'A'}],btn={disabled:false};
 const ctx={console,S,db:{},esc:s=>String(s),_tplOpts:t=>t.options||[],document:{getElementById:id=>nodes[id],querySelectorAll:()=>options,querySelector:q=>q==='.ftpl-editor'?null:btn},toast:m=>messages.push(m),doc:(db,col,id)=>({col,id}),updateDoc:async(ref,data)=>{writes.push({ref,data});Object.assign((ref.col==='fieldTemplates'?S.fieldTemplates:S[ref.col]).find(e=>e.id===ref.id),data);},loadData:async()=>{}};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(code,ctx);return {ctx,S,nodes,writes,messages,options};
}
test('renomeia sem perder valores e salva a ordem das opções',async()=>{const a=app();await a.ctx.saveEditFieldTpl('t','s');assert.equal(a.S.items[0].extra_fields['Novo nome'],'A');assert.equal(a.S.items[0].extra_fields.Observação,'Preservada');assert.equal(a.S.fieldTemplates[0].field_name,'Novo nome');assert.equal(a.S.fieldTemplates[0].options.join(','),'B,A');});
test('rejeita nomes duplicados e listas vazias antes de gravar',async()=>{const a=app();a.nodes['ftpl-edit-name-t'].value='Outro';await a.ctx.saveEditFieldTpl('t','s');assert.equal(a.writes.length,0);a.nodes['ftpl-edit-name-t'].value='Novo';a.options.length=0;await a.ctx.saveEditFieldTpl('t','s');assert.equal(a.writes.length,0);});
test('arrastar salva ordem e impede misturar escopos',async()=>{const a=app();const ev={preventDefault(){},dataTransfer:{getData:()=> 't'}};await a.ctx.dropFieldTpl(ev,'u');assert.equal(a.ctx.getFieldTpls('s','item')[0].id,'t');assert.equal(a.writes.length,2);a.S.fieldTemplates[1].scope='subitem';a.writes.length=0;await a.ctx.dropFieldTpl(ev,'u');assert.equal(a.writes.length,0);});
